### ISSUE TITLE
Problem parsing the package

### ISSUE THREAD

**Issue by XxTWMLxX** [linuxct/PhoneAccountDetector#2]
Tried to install the prebuilt appre-release apk and get problem parsing package error.

**Comment by linuxct** [comment]
Please provide logs. What Android version are you using?

**Comment by lawtancool** [comment]
I got this error on Android 9 on a Samsung Galaxy S8+. 

It seems that this app targets minimum Android 10, which makes sense since Google claims that the vulnerability only affects Android 10 and up. 

That being said, Android 9 still has the PhoneAccount functionality, so it would be nice if this app could be updated to support Android 9. Even though the emergency services bug shouldn't be there, it would still be useful for spotting apps that are creating excessive PhoneAccount instances. @linuxct

**Comment by XxTWMLxX** [comment]
im on a a8 and a oneplus 6 both on versions of android 9. so that seems to be correct that it may target android 10.

**Comment by linuxct** [comment]
> That being said, Android 9 still has the PhoneAccount functionality, so it would be nice if this app could be updated to support Android 9. Even though the emergency services bug shouldn't be there, it would still be useful for spotting apps that are creating excessive PhoneAccount instances. @linuxct

Support added, @lawtancool @XxTWMLxX please check [tag "1.1"](https://github.com/linuxct/PhoneAccountDetector/releases/tag/1.1).
